---
title: "Initial Reflections"
description: "Overview of my background in digital design and goals in E155."
author: "Eoin O'Connell"
date: "8/29/25"
categories:
  - reflection
draft: false
---

This is my third digital design class at Harvey Mudd, starting with E85: Digital Electronics and Computer Engineering, followed by E154: System-on-Chip Design, and now E155: Microprocessor Systems Design and Application.

Last summer I worked as a Physical Design intern at Tenstorrent, working on a RISC-V processor, so I am excited to get exposure to a completely different part of computer engineering, for very different applications.

I expect this class to be quite challenging, particularly with time managament. My goals are to stay multiple days ahead of due dates---not my normal inclination---to avoid long nights and extra stress if possible.

I am quite excited for a lot of the labs, particularly the 7 segment display lab, as well as the ditial audio lab. I think the 7 segment display is a very clear application that has a lot of uses, and I think it would be cool to connect multiple displays together to be able to print out longer messages. Additionally, as a musician, I am excited to work on the digital audio lab, and would be excited to expand this to include a keyboard.

Overall, I am very excited to see where this class takes me.

